feat(Terra): CW-5715- Terra Normal transfer
CoolBitX-Technology/coolwallet-sdk pull request #325
Opened 2022-03-17 08:48 UTC by kanitsu

Terra normal transfer with changeable tx and fee denom.
Can also select between main net and test net.

2022-03-17 08:48 UTC, cbx-tech commented
Task linked: [CW-5715 [SDK] Terra SDK - Terra normal transfer](https://app.clickup.com/t/25577573/CW-5715)

2022-03-17 09:32 UTC, skchang0710 requested changes

2022-03-17 09:32 UTC, skchang0710 commented on packages/coin-terra/src/config/params.ts
> +	UNDELEGATE = '/cosmos.staking.v1beta1.MsgUndelegate',
mix tab and space

2022-03-18 03:18 UTC, skchang0710 approved these changes

2022-03-18 03:25 UTC, hank121314 submitted a review, later dismissed

2022-03-21 02:28 UTC, skchang0710 approved these changes

2022-03-21 02:28 UTC, srt1678 approved these changes

2022-03-21 02:28 UTC, merged